// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $favoritos_index from "./routes/favoritos/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $AdicionaFavoritos from "./islands/AdicionaFavoritos.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Logger from "./islands/Logger.tsx";
import * as $RemoveFavoritos from "./islands/RemoveFavoritos.tsx";
import * as $SearchBar from "./islands/SearchBar.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/joke.ts": $api_joke,
    "./routes/favoritos/index.tsx": $favoritos_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AdicionaFavoritos.tsx": $AdicionaFavoritos,
    "./islands/Counter.tsx": $Counter,
    "./islands/Logger.tsx": $Logger,
    "./islands/RemoveFavoritos.tsx": $RemoveFavoritos,
    "./islands/SearchBar.tsx": $SearchBar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
